//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.View.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing items.
        /// </summary>
        internal static string AdminFeatureView {
            get {
                return ResourceManager.GetString("AdminFeatureView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0. Exit.
        /// </summary>
        internal static string AdminOption0 {
            get {
                return ResourceManager.GetString("AdminOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Admin Feature.
        /// </summary>
        internal static string AdminOption1 {
            get {
                return ResourceManager.GetString("AdminOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password:.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username:.
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  1. Login.
        /// </summary>
        internal static string LoginOption {
            get {
                return ResourceManager.GetString("LoginOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login or Register:.
        /// </summary>
        internal static string LoginRegisterPrompt {
            get {
                return ResourceManager.GetString("LoginRegisterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new item.
        /// </summary>
        internal static string ManagerAddItem_ {
            get {
                return ResourceManager.GetString("ManagerAddItem ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing item.
        /// </summary>
        internal static string ManagerEditItem {
            get {
                return ResourceManager.GetString("ManagerEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0. Exit.
        /// </summary>
        internal static string ManagerOption0_ {
            get {
                return ResourceManager.GetString("ManagerOption0 ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. View Item List.
        /// </summary>
        internal static string ManagerOption1 {
            get {
                return ResourceManager.GetString("ManagerOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Add Item.
        /// </summary>
        internal static string ManagerOption2 {
            get {
                return ResourceManager.GetString("ManagerOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Edit Item.
        /// </summary>
        internal static string ManagerOption3 {
            get {
                return ResourceManager.GetString("ManagerOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Print Item Report.
        /// </summary>
        internal static string ManagerOption4 {
            get {
                return ResourceManager.GetString("ManagerOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. View History.
        /// </summary>
        internal static string ManagerOption5 {
            get {
                return ResourceManager.GetString("ManagerOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing history.
        /// </summary>
        internal static string ManagerViewHistory {
            get {
                return ResourceManager.GetString("ManagerViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing items.
        /// </summary>
        internal static string ManagerViewItem {
            get {
                return ResourceManager.GetString("ManagerViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Register.
        /// </summary>
        internal static string RegisterOption {
            get {
                return ResourceManager.GetString("RegisterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new item.
        /// </summary>
        internal static string StaffAddItem {
            get {
                return ResourceManager.GetString("StaffAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing item.
        /// </summary>
        internal static string StaffEditItem {
            get {
                return ResourceManager.GetString("StaffEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing items.
        /// </summary>
        internal static string StaffViewItem {
            get {
                return ResourceManager.GetString("StaffViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View item list.
        /// </summary>
        internal static string ViewItem {
            get {
                return ResourceManager.GetString("ViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Admin Menu.
        /// </summary>
        internal static string WelcomeAdminMenu {
            get {
                return ResourceManager.GetString("WelcomeAdminMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Manager Menu.
        /// </summary>
        internal static string WelcomeManagerMenu {
            get {
                return ResourceManager.GetString("WelcomeManagerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Supermarket A Inventory Management App!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Staff menu .
        /// </summary>
        internal static string WelcomeMessageStaff {
            get {
                return ResourceManager.GetString("WelcomeMessageStaff", resourceCulture);
            }
        }
    }
}
